#!/usr/bin/env bash
# Acceptance Test: ACME after PEMs does not rewrite operator Routes; Edge may reload
# (ADR-0022 / ADR-0028). Soft-skips when Domain want-list is empty.
set -euo pipefail
# shellcheck source=lib.sh
source "$(cd "$(dirname "$0")" && pwd)/lib.sh"

require_ip
acceptance_host_session
[[ -n "${REPO_ROOT:-}" ]] || fail "fixture missing REPO_ROOT (run via ./test.sh acceptance)"

HOST="$(acceptance_route_fqdn)"
if [[ -z "${HOST}" ]]; then
  echo "SOFT-SKIP: empty Domain want-list — no FQDN for ACME Route-refresh probe"
  exit 0
fi

WL="acme-refresh"
FIX_DIR="$(acceptance_env_dir)"
mkdir -p "${FIX_DIR}"
acceptance_wl_track "${WL}"
trap 'acceptance_wl_cleanup' EXIT

mkdir -p "${FIX_DIR}/${WL}/routes"
acceptance_write_artifact_stubs "${FIX_DIR}/${WL}"
cat >"${FIX_DIR}/${WL}/manifest.json" <<EOF
{
  "intent": "run",
  "source": "internal"
}
EOF
MARKER="# operator-route-marker-${WL}"
cat >"${FIX_DIR}/${WL}/routes/probe.conf" <<EOF
${MARKER}
location = /acme-refresh-probe {
    default_type text/plain;
    return 200 'acme-refresh-ok';
}
EOF
acceptance_bind_route_fragment "${FIX_DIR}/${WL}" "routes/probe.conf" "${HOST}"

host_ssh \
  "rm -rf /var/lib/host-volume/internals/workloads/${WL}"

"${REPO_ROOT}/internals/ensure-workload.sh" "${WL}" --env "${PLATFORM_ENV:-test}"
ensure_edge_route_fulfillment

route_before="$(host_ssh \
  "cat /var/lib/host-volume/data/components/edge/routes/${WL}--${HOST}.conf")"
echo "${route_before}" | grep -q "${MARKER}" \
  || fail "operator Route marker missing before ACME"
pass "Operator Route fragment installed before ACME"

host_ssh bash -s <<REMOTE
set -euo pipefail
UID_NUM="\$(id -u platform)"
export XDG_RUNTIME_DIR="/run/user/\${UID_NUM}"
systemctl start "user@\${UID_NUM}.service"
runuser -u platform -- env XDG_RUNTIME_DIR="\$XDG_RUNTIME_DIR" \
  systemctl --user stop edge-acme.service 2>/dev/null || true
runuser -u platform -- env XDG_RUNTIME_DIR="\$XDG_RUNTIME_DIR" EDGE_ACME_ISSUE=0 \
  /var/lib/host-volume/internals/components/edge/acme-run.sh
REMOTE

route_after="$(host_ssh \
  "cat /var/lib/host-volume/data/components/edge/routes/${WL}--${HOST}.conf")"
[[ "${route_after}" == "${route_before}" ]] \
  || fail "ACME must not rewrite operator Route file contents"
echo "${route_after}" | grep -q 'Generated by Propraetor' \
  && fail "ACME must not inject projected Route shells" || true
pass "ACME oneshot leaves operator Route bytes unchanged"
